from .base import Base
from .tables.planning.affectation_machine import AffectationMachine
from .tables.planning.pointages import Pointage
from .tables.instrument_controle import InstrumentControle
from .tables.controle_piece import ControlePiece
from .tables.epi import EPI
from .tables.epi_utilisateur import EPIUtilisateur
from .tables.audit_qualite import AuditQualite
from .tables.non_conformites import NonConformite
from .tables.documents_qualite import DocumentQualite
from .tables.ged.documents_reglementaires import DocumentsReglementaires
from .tables.analyse_fichiers import AnalyseFichier
from .tables.ia_logs import IALogs
from .tables.liaison import machine_outil
from .tables.utilisateur import Utilisateur
from .tables.droit import Droit
from .tables.droit_acces import DroitAcces
from .tables.gestion_acces import GestionAcces
from .tables.rh import RHs
from .tables.absence import Absence
from .tables.formation import Formation
from .tables.sanction import Sanction
from .tables.entretien import Entretien
from .tables.rh.notation import NotationRH
from .tables.ged.document_rh import DocumentRH
from .tables.crm.clients import Client
from .tables.achat.fournisseurs import Fournisseur
from .tables.evaluations_fournisseur import EvaluationFournisseur
from .tables.devis import Devis
from .tables.achat.commandes import Commande
from .tables.commande_pieces import CommandePiece
from .tables.factures import Facture
from .tables.piece import Piece
from .tables.programme_piece import ProgrammePiece
from .tables.postprocesseur import PostProcesseur
from .tables.machine import Machine
from .tables.metrics_machines import MetricsMachine
from .tables.gmao.maintenance import Maintenance
from .tables.gammes_production import GammeProduction
from .tables.traceabilite.tracabilite import Tracabilite
from .tables.production import Production
from .tables.liaison import machine_outil
from .tables.employe import Employe

