# Importer ici tous les modèles utilisés dans la V1
from backend.db.models.tables.crm.client import Client
from backend.db.models.tables.crm.contact_client import ContactClient
from backend.db.models.tables.crm.adresse_client import AdresseClient
from backend.db.models.tables.achat.fournisseurs import Fournisseur
from backend.db.models.tables.achat.commandes_fournisseur import CommandeFournisseur
from backend.db.models.tables.achat.lignes_commande_fournisseur import LigneCommandeFournisseur
from backend.db.models.tables.achat.receptions import Reception
from backend.db.models.tables.achat.lignes_reception import LigneReception
from backend.db.models.tables.stock.stock import Stock
from backend.db.models.tables.stock.produit import Produit
from backend.db.models.tables.stock.materiau import Materiau
from backend.db.models.tables.production.gammes_production import GammeProduction
from backend.db.models.tables.production.machine import Machine
from backend.db.models.tables.production.outils import Outil
from backend.db.models.tables.rh.employe import Employe
from backend.db.models.tables.securite.utilisateur import Utilisateur
from backend.db.models.tables.securite.role_utilisateur import RoleUtilisateur
from backend.db.models.tables.finance.devis import Devis
from backend.db.models.tables.finance.ligne_devis import LigneDevis
from backend.db.models.tables.logistique.bordereau_livraison import BordereauLivraison
from backend.db.models.tables.entreprise.entreprise import Entreprise
from backend.db.models.tables.planning.planning_machine import PlanningMachine
from backend.db.models.base import Base
