"""Initialisation propre de la base

Revision ID: 205934d38771
Revises: ee4d55bcaf69
Create Date: 2025-03-22 18:31:12.815898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205934d38771'
down_revision: Union[str, None] = 'ee4d55bcaf69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance', sa.Column('materiau_id', sa.Integer(), nullable=True))
    op.add_column('finance', sa.Column('epi_id', sa.Integer(), nullable=True))
    op.add_column('finance', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.add_column('finance', sa.Column('utilisateur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'finance', 'instruments_controle', ['instrument_id'], ['id'])
    op.create_foreign_key(None, 'finance', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.create_foreign_key(None, 'finance', 'materiaux', ['materiau_id'], ['id'])
    op.create_foreign_key(None, 'finance', 'epi', ['epi_id'], ['id'])
    op.add_column('qhse', sa.Column('instrument_controle_id', sa.Integer(), nullable=True))
    op.add_column('qhse', sa.Column('epi_id', sa.Integer(), nullable=True))
    op.add_column('qhse', sa.Column('materiau_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'qhse', 'instruments_controle', ['instrument_controle_id'], ['id'])
    op.create_foreign_key(None, 'qhse', 'epi', ['epi_id'], ['id'])
    op.create_foreign_key(None, 'qhse', 'materiaux', ['materiau_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qhse', type_='foreignkey')
    op.drop_constraint(None, 'qhse', type_='foreignkey')
    op.drop_constraint(None, 'qhse', type_='foreignkey')
    op.drop_column('qhse', 'materiau_id')
    op.drop_column('qhse', 'epi_id')
    op.drop_column('qhse', 'instrument_controle_id')
    op.drop_constraint(None, 'finance', type_='foreignkey')
    op.drop_constraint(None, 'finance', type_='foreignkey')
    op.drop_constraint(None, 'finance', type_='foreignkey')
    op.drop_constraint(None, 'finance', type_='foreignkey')
    op.drop_column('finance', 'utilisateur_id')
    op.drop_column('finance', 'instrument_id')
    op.drop_column('finance', 'epi_id')
    op.drop_column('finance', 'materiau_id')
    # ### end Alembic commands ###
