"""Initialisation propre de la base

Revision ID: 30532a4d7a59
Revises: 4d5b41097383
Create Date: 2025-03-22 18:49:15.731700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30532a4d7a59'
down_revision: Union[str, None] = '4d5b41097383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('type_absence', sa.String(length=100), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entretiens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('type_entretien', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('actions_prevues', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('organisme', sa.String(length=150), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('certification', sa.String(length=150), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notations_rh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('date_evaluation', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('type_sanction', sa.String(length=150), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rh', sa.Column('date_debut', sa.DateTime(), nullable=True))
    op.add_column('rh', sa.Column('date_fin', sa.DateTime(), nullable=True))
    op.add_column('rh', sa.Column('statut_administratif', sa.String(length=100), nullable=True))
    op.add_column('rh', sa.Column('salaire_brut', sa.Float(), nullable=True))
    op.add_column('rh', sa.Column('remarques', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rh', 'remarques')
    op.drop_column('rh', 'salaire_brut')
    op.drop_column('rh', 'statut_administratif')
    op.drop_column('rh', 'date_fin')
    op.drop_column('rh', 'date_debut')
    op.drop_table('sanctions')
    op.drop_table('notations_rh')
    op.drop_table('formations')
    op.drop_table('entretiens')
    op.drop_table('absences')
    # ### end Alembic commands ###
