"""Initialisation propre de la base

Revision ID: 4d5b41097383
Revises: e370ec6a0953
Create Date: 2025-03-22 18:34:16.126718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5b41097383'
down_revision: Union[str, None] = 'e370ec6a0953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('robotique_machine_id_fkey', 'robotique', type_='foreignkey')
    op.drop_constraint('robotique_utilisateur_id_fkey', 'robotique', type_='foreignkey')
    op.drop_column('robotique', 'utilisateur_id')
    op.drop_column('robotique', 'machine_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robotique', sa.Column('machine_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('robotique', sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('robotique_utilisateur_id_fkey', 'robotique', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.create_foreign_key('robotique_machine_id_fkey', 'robotique', 'machines', ['machine_id'], ['id'])
    # ### end Alembic commands ###
