"""Initialisation des tables avec pieces

Revision ID: 519326ac2c89
Revises: 
Create Date: 2025-03-22 16:37:54.581463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519326ac2c89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('epi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('seuil_alerte', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_transaction', sa.String(length=100), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments_controle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('type_instrument', sa.String(length=100), nullable=True),
    sa.Column('date_calibrage', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('vitesse_max', sa.Float(), nullable=True),
    sa.Column('puissance', sa.Float(), nullable=True),
    sa.Column('nb_axes', sa.Integer(), nullable=True),
    sa.Column('axe_x_max', sa.Float(), nullable=True),
    sa.Column('axe_y_max', sa.Float(), nullable=True),
    sa.Column('axe_z_max', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('en_stock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('numero_plan', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_plan')
    )
    op.create_table('qhse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=True),
    sa.Column('conformité', sa.Boolean(), nullable=True),
    sa.Column('remarque', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('poste', sa.String(length=100), nullable=True),
    sa.Column('contrat', sa.String(length=100), nullable=True),
    sa.Column('temps_travail', sa.Float(), nullable=True),
    sa.Column('est_cadre', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robotique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_robot', sa.String(length=100), nullable=True),
    sa.Column('fonction', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('affectation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_commande', sa.DateTime(), nullable=True),
    sa.Column('bon_commande_client', sa.String(length=255), nullable=True),
    sa.Column('forcer_creation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('date_devis', sa.DateTime(), nullable=True),
    sa.Column('montant_total', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('scenarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gammes_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('outil_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('temps_prevu', sa.Float(), nullable=True),
    sa.Column('temps_reel', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['outil_id'], ['outils.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('afnor', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('durete', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commande_pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracabilite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamme_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('remarque', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gamme_id'], ['gammes_production.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracabilite')
    op.drop_table('commande_pieces')
    op.drop_table('materiaux')
    op.drop_table('gammes_production')
    op.drop_table('devis')
    op.drop_table('commandes')
    op.drop_table('utilisateurs')
    op.drop_table('robotique')
    op.drop_table('rh')
    op.drop_table('qhse')
    op.drop_table('pieces')
    op.drop_table('outils')
    op.drop_table('machines')
    op.drop_table('instruments_controle')
    op.drop_table('fournisseurs')
    op.drop_table('finance')
    op.drop_table('epi')
    op.drop_table('clients')
    # ### end Alembic commands ###
