"""Initial tables

Revision ID: 80986cdb89c3
Revises: a17152685f65
Create Date: 2025-03-23 19:21:23.152774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80986cdb89c3'
down_revision: Union[str, None] = 'a17152685f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_qhse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=True),
    sa.Column('type_document', sa.String(length=100), nullable=True),
    sa.Column('date_emission', sa.DateTime(), nullable=True),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.Column('fichier', sa.String(length=255), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objet_type', sa.String(length=100), nullable=True),
    sa.Column('objet_id', sa.Integer(), nullable=True),
    sa.Column('qr_code_data', sa.String(length=255), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents_rh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('type_document', sa.String(length=100), nullable=True),
    sa.Column('chemin_fichier', sa.String(length=255), nullable=True),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('droits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('autorisation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations_fournisseur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('date_evaluation', sa.DateTime(), nullable=True),
    sa.Column('critere', sa.String(length=150), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gestion_acces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('peut_lire', sa.Boolean(), nullable=True),
    sa.Column('peut_ecrire', sa.Boolean(), nullable=True),
    sa.Column('peut_supprimer', sa.Boolean(), nullable=True),
    sa.Column('peut_valider', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_processeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('logiciel', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('fichier', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charges_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('gamme_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['gamme_id'], ['gammes_production.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('siret', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('tva_intracom', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('secteur_activite', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('site_web', sa.String(length=150), nullable=True))
    op.add_column('clients', sa.Column('commentaire', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'clients', ['email'])
    op.add_column('controle_piece', sa.Column('remarque', sa.Text(), nullable=True))
    op.add_column('fournisseurs', sa.Column('tva', sa.String(length=50), nullable=True))
    op.add_column('fournisseurs', sa.Column('catalogue_interactif', sa.String(length=255), nullable=True))
    op.add_column('gammes_production', sa.Column('moyen_controle', sa.String(length=100), nullable=True))
    op.add_column('gammes_production', sa.Column('programme_piece', sa.String(length=255), nullable=True))
    op.add_column('gammes_production', sa.Column('longueur_debit', sa.Float(), nullable=True))
    op.add_column('gammes_production', sa.Column('nombre_debits', sa.Integer(), nullable=True))
    op.add_column('instruments_controle', sa.Column('numero_serie', sa.String(length=100), nullable=True))
    op.add_column('instruments_controle', sa.Column('date_prochaine_calibration', sa.DateTime(), nullable=True))
    op.add_column('instruments_controle', sa.Column('en_service', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'instruments_controle', ['numero_serie'])
    op.add_column('machines', sa.Column('commande_numerique', sa.String(length=100), nullable=True))
    op.add_column('machines', sa.Column('post_processeur', sa.String(length=255), nullable=True))
    op.add_column('machines', sa.Column('logiciel_fao', sa.String(length=100), nullable=True))
    op.add_column('materiaux', sa.Column('est_aeronautique', sa.Boolean(), nullable=True))
    op.add_column('materiaux', sa.Column('certificat_matiere', sa.String(length=255), nullable=True))
    op.alter_column('materiaux', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('materiaux', 'type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('outils', sa.Column('diametre', sa.Float(), nullable=True))
    op.add_column('outils', sa.Column('longueur', sa.Float(), nullable=True))
    op.add_column('outils', sa.Column('fournisseur_id', sa.Integer(), nullable=True))
    op.add_column('outils', sa.Column('ref_fournisseur', sa.String(length=100), nullable=True))
    op.add_column('outils', sa.Column('catalogue_url', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'outils', 'fournisseurs', ['fournisseur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outils', type_='foreignkey')
    op.drop_column('outils', 'catalogue_url')
    op.drop_column('outils', 'ref_fournisseur')
    op.drop_column('outils', 'fournisseur_id')
    op.drop_column('outils', 'longueur')
    op.drop_column('outils', 'diametre')
    op.alter_column('materiaux', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('materiaux', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('materiaux', 'certificat_matiere')
    op.drop_column('materiaux', 'est_aeronautique')
    op.drop_column('machines', 'logiciel_fao')
    op.drop_column('machines', 'post_processeur')
    op.drop_column('machines', 'commande_numerique')
    op.drop_constraint(None, 'instruments_controle', type_='unique')
    op.drop_column('instruments_controle', 'en_service')
    op.drop_column('instruments_controle', 'date_prochaine_calibration')
    op.drop_column('instruments_controle', 'numero_serie')
    op.drop_column('gammes_production', 'nombre_debits')
    op.drop_column('gammes_production', 'longueur_debit')
    op.drop_column('gammes_production', 'programme_piece')
    op.drop_column('gammes_production', 'moyen_controle')
    op.drop_column('fournisseurs', 'catalogue_interactif')
    op.drop_column('fournisseurs', 'tva')
    op.drop_column('controle_piece', 'remarque')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'commentaire')
    op.drop_column('clients', 'site_web')
    op.drop_column('clients', 'secteur_activite')
    op.drop_column('clients', 'tva_intracom')
    op.drop_column('clients', 'siret')
    op.drop_table('charges_machine')
    op.drop_table('post_processeurs')
    op.drop_table('gestion_acces')
    op.drop_table('evaluations_fournisseur')
    op.drop_table('droits')
    op.drop_table('documents_rh')
    op.drop_table('qr_codes')
    op.drop_table('documents_qhse')
    # ### end Alembic commands ###
