"""Initial tables

Revision ID: a091665b47a1
Revises: 18374612a667
Create Date: 2025-03-24 11:04:57.647294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a091665b47a1'
down_revision: Union[str, None] = '18374612a667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat_rh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode', sa.String(length=20), nullable=False),
    sa.Column('type_stat', sa.String(length=50), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('precision', sa.String(length=20), nullable=True),
    sa.Column('date_calcul', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lignes_facture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode', sa.String(length=20), nullable=False),
    sa.Column('type_stat', sa.String(length=50), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('sous_categorie', sa.String(length=100), nullable=True),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('source_finance_id', sa.Integer(), nullable=True),
    sa.Column('devise', sa.String(length=10), nullable=True),
    sa.Column('precision', sa.String(length=20), nullable=True),
    sa.Column('date_calcul', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_finance_id'], ['finance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode', sa.String(length=20), nullable=False),
    sa.Column('type_stat', sa.String(length=50), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('precision', sa.String(length=20), nullable=True),
    sa.Column('date_calcul', sa.DateTime(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('gamme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gamme_id'], ['gammes_production.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audits_qualite', sa.Column('responsable_nom', sa.String(length=100), nullable=False))
    op.alter_column('audits_qualite', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('audits_qualite', 'type_audit',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('audits_qualite', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('audits_qualite', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audits_qualite', 'responsable')
    op.alter_column('charges_machine', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('charges_machine', 'date_debut',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('charges_machine', 'date_fin',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('charges_machine', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('commande_pieces', 'commande_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('commande_pieces', 'piece_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('commande_pieces', 'quantite',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('commande_pieces_piece_id_fkey', 'commande_pieces', type_='foreignkey')
    op.drop_constraint('commande_pieces_commande_id_fkey', 'commande_pieces', type_='foreignkey')
    op.create_foreign_key(None, 'commande_pieces', 'commandes', ['commande_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'commande_pieces', 'pieces', ['piece_id'], ['id'], ondelete='CASCADE')
    op.add_column('commandes', sa.Column('code_statut', sa.String(length=20), nullable=True))
    op.add_column('commandes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('commandes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('controle_piece', 'instrument_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('controle_piece', 'piece_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('controle_piece', 'resultat',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('controle_piece', 'date_controle',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('documents_qhse', sa.Column('categorie', sa.String(length=100), nullable=True))
    op.alter_column('documents_qhse', 'titre',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('documents_qhse', 'type_document',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('documents_qhse', 'date_emission',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('documents_qhse', 'fichier',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('documents_qualite', sa.Column('categorie', sa.String(length=100), nullable=True))
    op.alter_column('documents_qualite', 'type_document',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('documents_qualite', 'fichier_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('documents_reglementaires', sa.Column('categorie', sa.String(length=100), nullable=True))
    op.alter_column('documents_reglementaires', 'type_document',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('documents_reglementaires', 'date_edition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('documents_reglementaires', 'fichier_stocke',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('epi', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('epi_utilisateur', 'utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('epi_utilisateur', 'epi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('epi_utilisateur', 'date_distribution',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('epi_utilisateur', 'quantite',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('factures', sa.Column('code_statut', sa.String(length=20), nullable=True))
    op.add_column('factures', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('factures', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('factures', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('finance', sa.Column('sous_categorie', sa.String(length=100), nullable=True))
    op.add_column('finance', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('finance', sa.Column('devise', sa.String(length=10), nullable=False))
    op.add_column('finance', sa.Column('periode', sa.String(length=20), nullable=True))
    op.add_column('finance', sa.Column('statut', sa.String(length=50), nullable=True))
    op.add_column('finance', sa.Column('moyen_paiement', sa.String(length=50), nullable=True))
    op.add_column('finance', sa.Column('code_statut', sa.String(length=20), nullable=True))
    op.add_column('finance', sa.Column('justificatif', sa.String(length=255), nullable=True))
    op.add_column('finance', sa.Column('type_justificatif', sa.String(length=50), nullable=True))
    op.add_column('finance', sa.Column('reference_facture', sa.String(length=100), nullable=True))
    op.add_column('finance', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.add_column('finance', sa.Column('outil_id', sa.Integer(), nullable=True))
    op.add_column('finance', sa.Column('machine_id', sa.Integer(), nullable=True))
    op.add_column('finance', sa.Column('facture_id', sa.Integer(), nullable=True))
    op.add_column('finance', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('finance', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('finance', 'type_transaction',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('finance', 'montant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('finance', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('finance', 'utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'finance', 'factures', ['facture_id'], ['id'])
    op.create_foreign_key(None, 'finance', 'instruments_controle', ['instrument_id'], ['id'])
    op.create_foreign_key(None, 'finance', 'outils', ['outil_id'], ['id'])
    op.create_foreign_key(None, 'finance', 'machines', ['machine_id'], ['id'])
    op.add_column('gammes_production', sa.Column('programme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gammes_production', 'programmes_piece', ['programme_id'], ['id'])
    op.drop_column('gammes_production', 'programme_piece')
    op.alter_column('instruments_controle', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('instruments_controle', 'type_instrument',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('instruments_controle', 'numero_serie',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('machines', 'post_processeur')
    op.alter_column('maintenance', 'type_maintenance',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('maintenance', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('non_conformites', 'origine',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('non_conformites', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('non_conformites', 'date_detection',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('non_conformites', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('non_conformites', 'utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pieces', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('pieces', 'numero_plan',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('planning_machine', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('planning_machine', 'plage_horaire',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('planning_machine', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('pointages', 'utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pointages', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pointages', 'gamme_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pointages', 'date_pointage',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('qhse', 'type_document',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('qr_codes', 'objet_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('qr_codes', 'objet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('qr_codes', 'qr_code_data',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('qr_codes', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'qr_codes', ['qr_code_data'])
    op.alter_column('utilisateurs', 'actif',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateurs', 'actif',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'qr_codes', type_='unique')
    op.alter_column('qr_codes', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('qr_codes', 'qr_code_data',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('qr_codes', 'objet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('qr_codes', 'objet_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('qhse', 'type_document',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('pointages', 'date_pointage',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pointages', 'gamme_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pointages', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pointages', 'utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('planning_machine', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('planning_machine', 'plage_horaire',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('planning_machine', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pieces', 'numero_plan',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('pieces', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('non_conformites', 'utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('non_conformites', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('non_conformites', 'date_detection',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('non_conformites', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('non_conformites', 'origine',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('maintenance', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('maintenance', 'type_maintenance',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('machines', sa.Column('post_processeur', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('instruments_controle', 'numero_serie',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('instruments_controle', 'type_instrument',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('instruments_controle', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('gammes_production', sa.Column('programme_piece', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gammes_production', type_='foreignkey')
    op.drop_column('gammes_production', 'programme_id')
    op.drop_constraint(None, 'finance', type_='foreignkey')
    op.drop_constraint(None, 'finance', type_='foreignkey')
    op.drop_constraint(None, 'finance', type_='foreignkey')
    op.drop_constraint(None, 'finance', type_='foreignkey')
    op.alter_column('finance', 'utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('finance', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('finance', 'montant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('finance', 'type_transaction',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('finance', 'updated_at')
    op.drop_column('finance', 'created_at')
    op.drop_column('finance', 'facture_id')
    op.drop_column('finance', 'machine_id')
    op.drop_column('finance', 'outil_id')
    op.drop_column('finance', 'instrument_id')
    op.drop_column('finance', 'reference_facture')
    op.drop_column('finance', 'type_justificatif')
    op.drop_column('finance', 'justificatif')
    op.drop_column('finance', 'code_statut')
    op.drop_column('finance', 'moyen_paiement')
    op.drop_column('finance', 'statut')
    op.drop_column('finance', 'periode')
    op.drop_column('finance', 'devise')
    op.drop_column('finance', 'description')
    op.drop_column('finance', 'sous_categorie')
    op.alter_column('factures', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('factures', 'updated_at')
    op.drop_column('factures', 'created_at')
    op.drop_column('factures', 'code_statut')
    op.alter_column('epi_utilisateur', 'quantite',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('epi_utilisateur', 'date_distribution',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('epi_utilisateur', 'epi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('epi_utilisateur', 'utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('epi', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('documents_reglementaires', 'fichier_stocke',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents_reglementaires', 'date_edition',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents_reglementaires', 'type_document',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('documents_reglementaires', 'categorie')
    op.alter_column('documents_qualite', 'fichier_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents_qualite', 'type_document',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('documents_qualite', 'categorie')
    op.alter_column('documents_qhse', 'fichier',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents_qhse', 'date_emission',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents_qhse', 'type_document',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('documents_qhse', 'titre',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('documents_qhse', 'categorie')
    op.alter_column('controle_piece', 'date_controle',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('controle_piece', 'resultat',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('controle_piece', 'piece_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('controle_piece', 'instrument_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('commandes', 'updated_at')
    op.drop_column('commandes', 'created_at')
    op.drop_column('commandes', 'code_statut')
    op.drop_constraint(None, 'commande_pieces', type_='foreignkey')
    op.drop_constraint(None, 'commande_pieces', type_='foreignkey')
    op.create_foreign_key('commande_pieces_commande_id_fkey', 'commande_pieces', 'commandes', ['commande_id'], ['id'])
    op.create_foreign_key('commande_pieces_piece_id_fkey', 'commande_pieces', 'pieces', ['piece_id'], ['id'])
    op.alter_column('commande_pieces', 'quantite',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('commande_pieces', 'piece_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('commande_pieces', 'commande_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('charges_machine', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('charges_machine', 'date_fin',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('charges_machine', 'date_debut',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('charges_machine', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('audits_qualite', sa.Column('responsable', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('audits_qualite', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audits_qualite', 'statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('audits_qualite', 'type_audit',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('audits_qualite', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('audits_qualite', 'responsable_nom')
    op.drop_table('stat_production')
    op.drop_table('stat_finance')
    op.drop_table('lignes_facture')
    op.drop_table('stat_rh')
    # ### end Alembic commands ###
