"""Initialisation propre de la base

Revision ID: b1032bdd16c6
Revises: 519326ac2c89
Create Date: 2025-03-22 16:59:36.220319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1032bdd16c6'
down_revision: Union[str, None] = '519326ac2c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epi', sa.Column('utilisateur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'epi', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.add_column('finance', sa.Column('utilisateur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'finance', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.add_column('instruments_controle', sa.Column('utilisateur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instruments_controle', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.add_column('qhse', sa.Column('utilisateur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'qhse', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.add_column('rh', sa.Column('utilisateur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rh', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.drop_column('rh', 'nom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rh', sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rh', type_='foreignkey')
    op.drop_column('rh', 'utilisateur_id')
    op.drop_constraint(None, 'qhse', type_='foreignkey')
    op.drop_column('qhse', 'utilisateur_id')
    op.drop_constraint(None, 'instruments_controle', type_='foreignkey')
    op.drop_column('instruments_controle', 'utilisateur_id')
    op.drop_constraint(None, 'finance', type_='foreignkey')
    op.drop_column('finance', 'utilisateur_id')
    op.drop_constraint(None, 'epi', type_='foreignkey')
    op.drop_column('epi', 'utilisateur_id')
    # ### end Alembic commands ###
