"""Ajout de la colonne responsable dans AuditQualite

Revision ID: b41c0a8ebfa6
Revises: f8b697e4886c
Create Date: 2025-03-27 21:38:14.594270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41c0a8ebfa6'
down_revision: Union[str, None] = 'f8b697e4886c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits_qualite', sa.Column('responsable', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'audits_qualite', 'utilisateurs', ['responsable'], ['id'])
    op.drop_column('audits_qualite', 'responsable_nom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits_qualite', sa.Column('responsable_nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audits_qualite', type_='foreignkey')
    op.drop_column('audits_qualite', 'responsable')
    # ### end Alembic commands ###
