"""Initialisation propre de la base

Revision ID: c0d910320071
Revises: b1032bdd16c6
Create Date: 2025-03-22 17:21:18.720278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d910320071'
down_revision: Union[str, None] = 'b1032bdd16c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_outil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('outil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['outil_id'], ['outils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('commandes', sa.Column('machine_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commandes', 'machines', ['machine_id'], ['id'])
    op.add_column('devis', sa.Column('piece_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devis', 'pieces', ['piece_id'], ['id'])
    op.drop_constraint('epi_utilisateur_id_fkey', 'epi', type_='foreignkey')
    op.drop_column('epi', 'utilisateur_id')
    op.drop_constraint('finance_utilisateur_id_fkey', 'finance', type_='foreignkey')
    op.drop_column('finance', 'utilisateur_id')
    op.add_column('gammes_production', sa.Column('materiau_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gammes_production', 'materiaux', ['materiau_id'], ['id'])
    op.add_column('instruments_controle', sa.Column('conforme_qhse', sa.Boolean(), nullable=True))
    op.drop_constraint('instruments_controle_utilisateur_id_fkey', 'instruments_controle', type_='foreignkey')
    op.drop_column('instruments_controle', 'utilisateur_id')
    op.add_column('qhse', sa.Column('conformite', sa.Boolean(), nullable=True))
    op.drop_constraint('qhse_utilisateur_id_fkey', 'qhse', type_='foreignkey')
    op.drop_column('qhse', 'conformité')
    op.drop_column('qhse', 'utilisateur_id')
    op.add_column('rh', sa.Column('salaire', sa.Float(), nullable=True))
    op.add_column('utilisateurs', sa.Column('epi_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'utilisateurs', 'epi', ['epi_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utilisateurs', type_='foreignkey')
    op.drop_column('utilisateurs', 'epi_id')
    op.drop_column('rh', 'salaire')
    op.add_column('qhse', sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('qhse', sa.Column('conformité', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('qhse_utilisateur_id_fkey', 'qhse', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.drop_column('qhse', 'conformite')
    op.add_column('instruments_controle', sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('instruments_controle_utilisateur_id_fkey', 'instruments_controle', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.drop_column('instruments_controle', 'conforme_qhse')
    op.drop_constraint(None, 'gammes_production', type_='foreignkey')
    op.drop_column('gammes_production', 'materiau_id')
    op.add_column('finance', sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('finance_utilisateur_id_fkey', 'finance', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.add_column('epi', sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('epi_utilisateur_id_fkey', 'epi', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.drop_constraint(None, 'devis', type_='foreignkey')
    op.drop_column('devis', 'piece_id')
    op.drop_constraint(None, 'commandes', type_='foreignkey')
    op.drop_column('commandes', 'machine_id')
    op.drop_table('machine_outil')
    # ### end Alembic commands ###
