"""Initialisation propre de la base

Revision ID: e370ec6a0953
Revises: 205934d38771
Create Date: 2025-03-22 18:33:00.284465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e370ec6a0953'
down_revision: Union[str, None] = '205934d38771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robotique', sa.Column('utilisateur_id', sa.Integer(), nullable=True))
    op.add_column('robotique', sa.Column('machine_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'robotique', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.create_foreign_key(None, 'robotique', 'machines', ['machine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'robotique', type_='foreignkey')
    op.drop_constraint(None, 'robotique', type_='foreignkey')
    op.drop_column('robotique', 'machine_id')
    op.drop_column('robotique', 'utilisateur_id')
    # ### end Alembic commands ###
