"""Initialisation propre de la base

Revision ID: ee4d55bcaf69
Revises: ffa10b26ca36
Create Date: 2025-03-22 18:06:45.302366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4d55bcaf69'
down_revision: Union[str, None] = 'ffa10b26ca36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affectation_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_outil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('outil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['outil_id'], ['outils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controle_piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('resultat', sa.String(length=100), nullable=True),
    sa.Column('date_controle', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments_controle.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('epi_qhse_id_fkey', 'epi', type_='foreignkey')
    op.drop_constraint('epi_finance_id_fkey', 'epi', type_='foreignkey')
    op.drop_column('epi', 'qhse_id')
    op.drop_column('epi', 'finance_id')
    op.drop_constraint('finance_materiau_id_fkey', 'finance', type_='foreignkey')
    op.drop_column('finance', 'materiau_id')
    op.add_column('instruments_controle', sa.Column('conforme_qhse', sa.Boolean(), nullable=True))
    op.drop_constraint('instruments_controle_qhse_id_fkey', 'instruments_controle', type_='foreignkey')
    op.drop_constraint('instruments_controle_finance_id_fkey', 'instruments_controle', type_='foreignkey')
    op.drop_column('instruments_controle', 'qhse_id')
    op.drop_column('instruments_controle', 'finance_id')
    op.drop_constraint('outils_machine_id_fkey', 'outils', type_='foreignkey')
    op.drop_column('outils', 'machine_id')
    op.drop_constraint('qhse_materiau_id_fkey', 'qhse', type_='foreignkey')
    op.drop_column('qhse', 'materiau_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qhse', sa.Column('materiau_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('qhse_materiau_id_fkey', 'qhse', 'materiaux', ['materiau_id'], ['id'])
    op.add_column('outils', sa.Column('machine_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('outils_machine_id_fkey', 'outils', 'machines', ['machine_id'], ['id'])
    op.add_column('instruments_controle', sa.Column('finance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('instruments_controle', sa.Column('qhse_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('instruments_controle_finance_id_fkey', 'instruments_controle', 'finance', ['finance_id'], ['id'])
    op.create_foreign_key('instruments_controle_qhse_id_fkey', 'instruments_controle', 'qhse', ['qhse_id'], ['id'])
    op.drop_column('instruments_controle', 'conforme_qhse')
    op.add_column('finance', sa.Column('materiau_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('finance_materiau_id_fkey', 'finance', 'materiaux', ['materiau_id'], ['id'])
    op.add_column('epi', sa.Column('finance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('epi', sa.Column('qhse_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('epi_finance_id_fkey', 'epi', 'finance', ['finance_id'], ['id'])
    op.create_foreign_key('epi_qhse_id_fkey', 'epi', 'qhse', ['qhse_id'], ['id'])
    op.drop_table('controle_piece')
    op.drop_table('machine_outil')
    op.drop_table('affectation_machine')
    # ### end Alembic commands ###
