"""Correction des relations MetricsMachine

Revision ID: ff1768cc25ab
Revises: ff980a1daf0b
Create Date: 2025-03-27 22:00:31.154451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff1768cc25ab'
down_revision: Union[str, None] = 'ff980a1daf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.alter_column('metrics_machine', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_metrics_machine_id'), 'metrics_machine', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_machine_id'), table_name='metrics_machine')
    op.alter_column('metrics_machine', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.alter_column('machines', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
