"""Ajout de fournisseur_id dans GestionFiltrage

Revision ID: ff980a1daf0b
Revises: b41c0a8ebfa6
Create Date: 2025-03-27 21:44:48.942115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff980a1daf0b'
down_revision: Union[str, None] = 'b41c0a8ebfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gestion_filtrage', sa.Column('fournisseur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gestion_filtrage', 'fournisseurs', ['fournisseur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gestion_filtrage', type_='foreignkey')
    op.drop_column('gestion_filtrage', 'fournisseur_id')
    # ### end Alembic commands ###
