"""Initialisation propre de la base

Revision ID: ffa10b26ca36
Revises: 96c4d74bdc27
Create Date: 2025-03-22 17:41:06.281304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa10b26ca36'
down_revision: Union[str, None] = '96c4d74bdc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments_controle', sa.Column('finance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instruments_controle', 'finance', ['finance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instruments_controle', type_='foreignkey')
    op.drop_column('instruments_controle', 'finance_id')
    # ### end Alembic commands ###
